version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  target-branch: dev
- package-ecosystem: npm
  directory: "/pwa"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  target-branch: dev
- package-ecosystem: gradle
  directory: "/android"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  target-branch: dev
