name: Download Masterdata
description: Fetch the masterdata branch archive and place its contents into src/app/data
runs:
  using: composite
  steps:
    - name: Download Masterdata
      shell: bash
      run: wget https://github.com/TiloHeidasch/launchschedule/archive/refs/heads/masterdata.zip
    - name: Unzip Masterdata
      shell: bash
      run: unzip -qq ./masterdata.zip -d ./src/app/data/
    - name: Copy Masterdata
      shell: bash
      run: sudo cp ./src/app/data/launchschedule-masterdata/* ./src/app/data/
