name: Fetch Launches

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  fetchLaunches1:
    name: Fetch Launches 0-500
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 0 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches1
          path: src/app/data/
  fetchLaunches2:
    name: Fetch Launches 500-1000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 500 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches2
          path: src/app/data/
  fetchLaunches3:
    name: Fetch Launches 1000-1500
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 1000 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches3
          path: src/app/data/
  fetchLaunches4:
    name: Fetch Launches 1500-2000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 1500 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches4
          path: src/app/data/
  fetchLaunches5:
    name: Fetch Launches 2000-2500
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 2000 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches5
          path: src/app/data/
  fetchLaunches6:
    name: Fetch Launches 2500-3000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 2500 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches6
          path: src/app/data/
  fetchLaunches7:
    name: Fetch Launches 3000-3500
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 3000 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches7
          path: src/app/data/
  fetchLaunches8:
    name: Fetch Launches 3500-4000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 3500 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches8
          path: src/app/data/
  fetchLaunches9:
    name: Fetch Launches 4000-4500
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 4000 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches9
          path: src/app/data/
  fetchLaunches10:
    name: Fetch Launches 4500-5000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 4500 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches10
          path: src/app/data/
  fetchLaunches11:
    name: Fetch Launches 5000-5500
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 5000 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches11
          path: src/app/data/
  fetchLaunches12:
    name: Fetch Launches 5500-6000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 5500 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches12
          path: src/app/data/
  fetchLaunches13:
    name: Fetch Launches 6000-6500
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 6000 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches13
          path: src/app/data/
  fetchLaunches14:
    name: Fetch Launches 6500-7000
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
      - name: Fetch Launches
        run: node scripts/fetchLaunches.ts 6500 500
      - name: Safe Data Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: launches14
          path: src/app/data/
  commit:
    name: Commit Master Data
    runs-on: ubuntu-latest
    needs: [
        fetchLaunches1,
        fetchLaunches2,
        fetchLaunches3,
        fetchLaunches4,
        fetchLaunches5,
        fetchLaunches6,
        fetchLaunches7,
        fetchLaunches8,
        fetchLaunches9,
        fetchLaunches10,
        fetchLaunches11,
        fetchLaunches12,
        fetchLaunches13,
        fetchLaunches14,
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: masterdata
      - name: Download Launches 0-500
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches1
          path: ./
      - name: Download Launches 500-1000
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches2
          path: ./
      - name: Download Launches 1000-1500
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches3
          path: ./
      - name: Download Launches 1500-2000
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches4
          path: ./
      - name: Download Launches 2000-2500
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches5
          path: ./
      - name: Download Launches 2500-3000
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches6
          path: ./
      - name: Download Launches 3000-3500
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches7
          path: ./
      - name: Download Launches 3500-4000
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches8
          path: ./
      - name: Download Launches 4000-4500
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches9
          path: ./
      - name: Download Launches 4500-5000
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches10
          path: ./
      - name: Download Launches 5000-5500
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches11
          path: ./
      - name: Download Launches 5500-6000
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches12
          path: ./
      - name: Download Launches 6000-6500
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches13
          path: ./
      - name: Download Launches 6500-7000
        uses: actions/download-artifact@v2.0.9
        with:
          name: launches14
          path: ./
      - name: Push to Masterdata branch
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: ./
          target_branch: masterdata
          commit_message: 'Updates Launches'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
