name: Fetch Masterdata

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  masterdata:
    name: Download and Merge Masterdata
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Agencies 0-500
        run: node scripts/masterdata/fetch.ts agencies agencies 0 500
      - name: Fetch Astronauts 0-500
        run: node scripts/masterdata/fetchAstronaut.ts 0 500
      - name: Fetch Astronauts 500-1000
        run: node scripts/masterdata/fetchAstronaut.ts 500 500
      - name: Fetch Launches 0-500
        run: node scripts/fetchLaunches.ts 0 500
      - name: Fetch Launches 500-1000
        run: node scripts/fetchLaunches.ts 500 500
      - name: Fetch Launches 1000-1500
        run: node scripts/fetchLaunches.ts 1000 500
      - name: Fetch Launches 1500-2000
        run: node scripts/fetchLaunches.ts 1500 500
      - name: Fetch Locations 0-500
        run: node scripts/masterdata/fetch.ts location locations 0 500
      - name: Fetch Pads 0-500
        run: node scripts/masterdata/fetch.ts pad pads 0 500
      - name: Fetch Previous Events 0-500
        run: node scripts/masterdata/fetch.ts event/previous previousevents 0 500
      - name: Fetch Previous Launches 0-500
        run: node scripts/masterdata/fetchPreviousLaunches.ts 0 500
      - name: Fetch Previous Launches 500-1000
        run: node scripts/masterdata/fetchPreviousLaunches.ts 500 500
      - name: Fetch Previous Launches 1000-1500
        run: node scripts/masterdata/fetchPreviousLaunches.ts 1000 500
      - name: Fetch Previous Launches 1500-2000
        run: node scripts/masterdata/fetchPreviousLaunches.ts 1500 500
      - name: Fetch Rockets 0-500
        run: node scripts/masterdata/fetch.ts config/launcher rockets 0 500
      - name: Fetch Spacecrafts 0-500
        run: node scripts/masterdata/fetch.ts config/spacecraft spacecrafts 0 500
      - name: Fetch Spacestations 0-500
        run: node scripts/masterdata/fetch.ts spacestation spacestations 0 500
      - name: Merge Agencies
        run: node scripts/masterdata/merge.ts agencies 500 500
      - name: Merge Astronauts
        run: node scripts/masterdata/merge.ts astronauts 1000 500
      - name: Merge Launches
        run: node scripts/mergeLaunches.ts 2000 500
      - name: Merge Locations
        run: node scripts/masterdata/merge.ts locations 500 500
      - name: Merge Pads
        run: node scripts/masterdata/merge.ts pads 500 500
      - name: Merge Previous Events
        run: node scripts/masterdata/merge.ts previousevents 500 500
      - name: Merge Previous Launches
        run: node scripts/masterdata/merge.ts previouslaunches 2000 500
      - name: Merge Rockets
        run: node scripts/masterdata/merge.ts rockets 500 500
      - name: Merge Spacecrafts
        run: node scripts/masterdata/merge.ts spacecrafts 500 500
      - name: Merge Spacestations
        run: node scripts/masterdata/merge.ts spacestations 500 500
      - name: Safe MasterData Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: masterdata
          path: src/app/data/
  upload:
    name: Upload Masterdata to branch
    runs-on: ubuntu-latest
    needs: masterdata
    steps:
      - name: Download Masterdata
        uses: actions/download-artifact@v2.0.9
        with:
          name: masterdata
          path: ./
      - name: Push to Masterdata branch
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: ./
          target_branch: masterdata
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
