name: Merge Masterdata

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  merge:
    name: Merge Master Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: masterdata
      - name: Create dirs
        run: mkdir src && mkdir src/app && mkdir src/app/data
      - name: Moves Data
        run: mv *.json src/app/data
      - name: Merge Agencies
        run: node scripts/masterdata/merge.ts agencies 500 500
      - name: Merge Astronauts
        run: node scripts/masterdata/merge.ts astronauts 1000 500
      - name: Merge Launches
        run: node scripts/mergeLaunches.ts 7000 500
      - name: Merge Locations
        run: node scripts/masterdata/merge.ts locations 500 500
      - name: Merge Pads
        run: node scripts/masterdata/merge.ts pads 500 500
      - name: Merge Previous Events
        run: node scripts/masterdata/merge.ts previousevents 500 500
      - name: Merge Previous Launches
        run: node scripts/masterdata/merge.ts previouslaunches 6500 500
      - name: Merge Rockets
        run: node scripts/masterdata/merge.ts rockets 500 500
      - name: Merge Spacecrafts
        run: node scripts/masterdata/merge.ts spacecrafts 500 500
      - name: Merge Spacestations
        run: node scripts/masterdata/merge.ts spacestations 500 500
      - name: Safe MasterData Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: masterdata
          path: src/app/data/
  upload:
    name: Upload Masterdata to branch
    runs-on: ubuntu-latest
    needs: merge
    steps:
      - name: Download Masterdata
        uses: actions/download-artifact@v2.0.9
        with:
          name: masterdata
          path: ./
      - name: Push to Masterdata branch
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: ./
          target_branch: masterdata
          commit_message: 'Updates Masterdata'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}